# Generated by Django 5.2.5 on 2025-08-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('location', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('tournament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GamesTournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GamesTournaments.team')),
                ('tournaments', models.ManyToManyField(default=None, to='GamesTournaments.tournament')),
            ],
        ),
    ]
