# Generated by Django 5.2.5 on 2025-08-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesTournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(default=None, null=True, to='GamesTournaments.player'),
        ),
    ]
