# Generated by Django 5.2.5 on 2025-11-30 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesTournaments', '0002_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'permissions': (('manage_roster', 'Може керувати складом гравців'),)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('manage_teams', 'Може створювати та видаляти команди'),)},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': (('manage_tournaments', 'Може створювати та видаляти турніри'),)},
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'team')},
        ),
    ]
