# Generated by Django 5.2.5 on 2025-11-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesTournaments', '0003_alter_player_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='teams/emblems/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/banners/'),
        ),
    ]
